services:
    jms_serializer.datetime_handler:
        class: Wk\AfterbuyApiBundle\Serializer\DateHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
    wk_afterbuy_api.xml.client:
        class: Wk\AfterbuyApiBundle\Services\Xml\Client
        arguments:
            - "%wk_afterbuy_api.user.id%"
            - "%wk_afterbuy_api.user.password%"
            - "%wk_afterbuy_api.partner.id%"
            - "%wk_afterbuy_api.partner.password%"
            - "%wk_afterbuy_api.error_language%"
        calls:
            - [setLogger, ["@logger"]]